# name: PR modified
# on:
#   push:
#     branches:
#       - master
#   pull_request:
#     branches:
#       - master
#     types: [ opened, synchronize, reopened ]
#   workflow_dispatch:
# permissions:
#   contents: write
#   packages: write
#   pull-requests: write
# jobs:
#   run-tests:
#     name: Run tests
#     runs-on: ubuntu-24.04
#     env:
#       DOTNET_INSTALL_DIR: "./.dotnet"
#     steps:
#       - name: Set PATH
#         run: echo "/home/runner/.dotnet/tools" >> $GITHUB_PATH
#       - name: Checkout
#         uses: actions/checkout@v5
#       - name: Setup dotnet
#         uses: actions/setup-dotnet@v5
#         with:
#           dotnet-version: 10.x
#           dotnet-quality: "ga"
#       - name: Run tests
#         run: dotnet test
